# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: smartapps/bitbucket-pipelines-php-mysql:stretch

pipelines:
  default:
    - step:
        script:
          - service mysql start
          - mysql -h localhost --user=root --password=root -e "CREATE DATABASE IF NOT EXISTS yii_starter_tests CHARACTER SET utf8 COLLATE utf8_general_ci;"
          - composer global require "fxp/composer-asset-plugin:^1.2.1"
          - composer install
          - cp config/params.php.sample config/params.php
          - cp config/db.php.sample config/db.php
          - cp config/mailer.php.sample config/mailer.php
          - php vendor/bin/codecept run